const fs=require("fs");
const os=require("os");
const path=require("path");
const crypto=require("crypto");
const {spawn,spawnSync}=require("child_process");

const norm=(v)=>String(v||"").replace(/\r/g,"").replace(/\u00a0/g," ").replace(/[\t\f\v ]+/g," ").replace(/\n{3,}/g,"\n\n").trim();
const decode=(v)=>String(v||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&#x([0-9a-f]+);/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(parseInt(n,10)));
const strip=(v)=>norm(decode(String(v||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>/gi,"\n\n").replace(/<\/div>/gi,"\n").replace(/<\/li>/gi,"\n").replace(/<[^>]+>/g," ")));
const clip=(v,n=280)=>{const t=norm(v);return t.length<=n?t:`${t.slice(0,Math.max(0,n-1)).trim()}…`;};
const slug=(v)=>String(v||"").toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,"-").replace(/^-+|-+$/g,"")||`file-${Date.now()}`;
const ensure=(d)=>fs.mkdirSync(d,{recursive:true});
const outPath=({outputPath,outputDir,defaultBaseName,extension})=>{if(outputPath){ensure(path.dirname(path.resolve(outputPath)));return path.resolve(outputPath);}const dir=path.resolve(outputDir||"./downloads");ensure(dir);return path.join(dir,`${defaultBaseName}${extension}`);};
const tmp=(ext,content)=>{const dir=path.join(os.tmpdir(),`opensearch-tools-${process.pid}`);ensure(dir);const file=path.join(dir,`${Date.now()}-${crypto.randomBytes(4).toString("hex")}${ext}`);if(content!==undefined)fs.writeFileSync(file,content,"utf8");return file;};
const rm=(file)=>{try{if(file)fs.rmSync(file,{force:true});}catch(_){}};
const titleOf=(html)=>norm(decode((String(html||"").match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||""));
function meta(html,key){for(const p of [new RegExp(`<meta[^>]+property=["']${key}["'][^>]+content=["']([^"']*)["'][^>]*>`,"i"),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+property=["']${key}["'][^>]*>`,"i"),new RegExp(`<meta[^>]+name=["']${key}["'][^>]+content=["']([^"']*)["'][^>]*>`,"i"),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+name=["']${key}["'][^>]*>`,"i")]){const m=String(html||"").match(p);if(m?.[1])return norm(decode(m[1]));}return "";}
const canonical=(html)=>((String(html||"").match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["'][^>]*>/i)||String(html||"").match(/<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["'][^>]*>/i)||[])[1]||"").trim();
function metaMap(html){const map={};const re=/<meta\b([^>]+)>/gi;let m=re.exec(String(html||""));while(m){const n=(m[1].match(/(?:name|property)=['"]([^'"]+)['"]/i)||[])[1];const c=(m[1].match(/content=['"]([^'"]*)['"]/i)||[])[1];if(n&&c)map[n.trim().toLowerCase()]=norm(decode(c));m=re.exec(String(html||""));}return map;}
function jsonLd(html){const arr=[];for(const block of String(html||"").match(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)||[]){const raw=(block.match(/<script[^>]*>([\s\S]*?)<\/script>/i)||[])[1];if(!raw)continue;try{const parsed=JSON.parse(raw.trim());if(Array.isArray(parsed))arr.push(...parsed);else arr.push(parsed);}catch(_){}}return arr;}
function links(html,base,limit=40){const out=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m=re.exec(String(html||""));while(m&&out.length<limit){const href=(m[1]||"").trim();if(href&&!href.startsWith("javascript:")){let abs=href;try{abs=new URL(href,base).toString();}catch(_){}out.push({href:abs,text:clip(strip(m[2]||""),120)});}m=re.exec(String(html||""));}return out;}
function heads(html){const out=[];const re=/<h([1-3])\b[^>]*>([\s\S]*?)<\/h\1>/gi;let m=re.exec(String(html||""));while(m&&out.length<20){const text=strip(m[2]||"");if(text)out.push({level:Number(m[1]),text});m=re.exec(String(html||""));}return out;}
const cleanHtml=(html)=>String(html||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<svg[\s\S]*?<\/svg>/gi," ").replace(/<iframe[\s\S]*?<\/iframe>/gi," ").replace(/<!--([\s\S]*?)-->/g," ");
function largest(html,tags){let best="";for(const tag of tags){const re=new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`,"gi");let m=re.exec(html);while(m){if(strip(m[1]).length>strip(best).length)best=m[1]||"";m=re.exec(html);}}return best;}
const pickMain=(html)=>{const c=cleanHtml(html);return largest(c,["article","main","section"])||largest(c,["div"])||c;};
const splitSentences=(v)=>String(v||"").split(/(?<=[.!?。！？])\s+/).map((s)=>s.trim()).filter(Boolean);
const points=(text,n=5)=>splitSentences(text).filter((s)=>s.length>=24).slice(0,n);
function htmlToMd(html){let md=String(html||"");md=md.replace(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi,(_,c)=>`# ${strip(c)}\n\n`).replace(/<h2\b[^>]*>([\s\S]*?)<\/h2>/gi,(_,c)=>`## ${strip(c)}\n\n`).replace(/<h3\b[^>]*>([\s\S]*?)<\/h3>/gi,(_,c)=>`### ${strip(c)}\n\n`).replace(/<li\b[^>]*>([\s\S]*?)<\/li>/gi,(_,c)=>`- ${strip(c)}\n`).replace(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi,(_,h,c)=>`[${strip(c)||h}](${h})`).replace(/<(strong|b)\b[^>]*>([\s\S]*?)<\/\1>/gi,(_,t,c)=>`**${strip(c)}**`).replace(/<(em|i)\b[^>]*>([\s\S]*?)<\/\1>/gi,(_,t,c)=>`_${strip(c)}_`).replace(/<p\b[^>]*>([\s\S]*?)<\/p>/gi,(_,c)=>`${strip(c)}\n\n`).replace(/<br\s*\/?>/gi,"\n");return strip(md).replace(/\n{3,}/g,"\n\n").trim();}
const esc=(v)=>String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
const mdInline=(v)=>esc(v).replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/_(.+?)_/g,"<em>$1</em>").replace(/\[(.+?)\]\((.+?)\)/g,'<a href="$2">$1</a>');
function mdToHtml(md,title="Document"){const lines=String(md||"").split(/\r?\n/);const html=[];let inList=false;for(const raw of lines){const line=raw.trim();if(!line){if(inList){html.push("</ul>");inList=false;}continue;}if(/^###\s+/.test(line)){if(inList){html.push("</ul>");inList=false;}html.push(`<h3>${mdInline(line.replace(/^###\s+/,""))}</h3>`);continue;}if(/^##\s+/.test(line)){if(inList){html.push("</ul>");inList=false;}html.push(`<h2>${mdInline(line.replace(/^##\s+/,""))}</h2>`);continue;}if(/^#\s+/.test(line)){if(inList){html.push("</ul>");inList=false;}html.push(`<h1>${mdInline(line.replace(/^#\s+/,""))}</h1>`);continue;}if(/^-\s+/.test(line)){if(!inList){html.push("<ul>");inList=true;}html.push(`<li>${mdInline(line.replace(/^-\s+/,""))}</li>`);continue;}if(inList){html.push("</ul>");inList=false;}html.push(`<p>${mdInline(line)}</p>`);}if(inList)html.push("</ul>");return `<!doctype html><html><head><meta charset="utf-8" /><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;margin:32px;line-height:1.6;color:#1f2937}h1,h2,h3{color:#111827}a{color:#2563eb}</style></head><body>${html.join("\n")}</body></html>`;}
async function fetchHtml(url,opt={}){const res=await fetch(url,{redirect:opt.redirect||"follow",headers:{"User-Agent":opt.userAgent||"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36","Accept":"text/html,application/xhtml+xml"}});if(!res.ok)throw new Error(`Failed to fetch page: ${res.status}`);return{html:await res.text(),finalUrl:res.url||url};}
function articlePayload({url,finalUrl,html,rendered}){const m=metaMap(html);const body=pickMain(html);const text=strip(body);const title=meta(html,"og:title")||meta(html,"twitter:title")||titleOf(html);const excerpt=meta(html,"description")||meta(html,"og:description")||clip(text,220);const byline=meta(html,"author")||meta(html,"article:author")||rendered?.heading||"";const site=meta(html,"og:site_name")||(()=>{try{return new URL(finalUrl||url).hostname.replace(/^www\./,"");}catch(_){return "";}})();return{url,final_url:finalUrl||url,canonical_url:canonical(html)||finalUrl||url,title,byline,site_name:site,excerpt,published_at:meta(html,"article:published_time")||meta(html,"pubdate")||null,lead_image:meta(html,"og:image")||meta(html,"twitter:image")||null,content_html:body.trim(),text,word_count:text?text.split(/\s+/).filter(Boolean).length:0,key_points:points(text),headings:heads(html),links:links(html,finalUrl||url),extraction_engine:rendered?"fetch+rendered-snapshot":"fetch-heuristic",meta:m,json_ld:jsonLd(html)};}
const schemaFields=(input={})=>{const names=[];if(Array.isArray(input.fields))names.push(...input.fields.map((v)=>String(v||"").trim()));if(Array.isArray(input.schema))names.push(...input.schema.map((v)=>String(v||"").trim()));else if(typeof input.schema==="string"&&input.schema.trim()){try{return schemaFields({schema:JSON.parse(input.schema),fields:names});}catch(_){names.push(...input.schema.split(/[\n,]/).map((v)=>v.trim()));}}else if(input.schema&&typeof input.schema==="object")names.push(...Object.keys(input.schema));return [...new Set(names.filter(Boolean))];};
function flat(v){if(v===null||v===undefined)return "";if(["string","number","boolean"].includes(typeof v))return String(v);if(Array.isArray(v))return v.map(flat).filter(Boolean).join(" | ");if(typeof v==="object")return v.name||v.url||"";return "";}
function inferField(field,ctx){const key=String(field||"").toLowerCase();const article=ctx.article||{};const meta=ctx.meta||{};const known={title:article.title,headline:article.title,description:article.excerpt,excerpt:article.excerpt,summary:clip(article.text,320),author:article.byline,byline:article.byline,site_name:article.site_name,published_at:article.published_at,date:article.published_at,canonical_url:article.canonical_url,image:article.lead_image,lead_image:article.lead_image,word_count:article.word_count,headings:article.headings?.map((i)=>i.text)||[],links:article.links||[]};if(Object.prototype.hasOwnProperty.call(known,key))return known[key];if(meta[key]||meta[`og:${key}`]||meta[`article:${key}`])return meta[key]||meta[`og:${key}`]||meta[`article:${key}`];for(const node of ctx.jsonLd||[]){if(node&&typeof node==="object"){for(const k of Object.keys(node)){if(k.toLowerCase()===key)return flat(node[k]);}}}const match=(ctx.text||"").match(new RegExp(`${key.replace(/[_\s]+/g,"[\\s_:-]*")}\\s*[:：-]\\s*([^\\n]{1,180})`,"i"));if(match?.[1])return norm(match[1]);return splitSentences(ctx.text||"").find((s)=>s.toLowerCase().includes(key.replace(/_/g," ")))||null;}
const run=(cmd,args,opt={})=>new Promise((resolve,reject)=>{const child=spawn(cmd,args,{stdio:["ignore","pipe","pipe"],...opt});let out="",err="";child.stdout.on("data",(c)=>out+=c.toString("utf8"));child.stderr.on("data",(c)=>err+=c.toString("utf8"));child.on("error",reject);child.on("exit",(code)=>code===0?resolve({stdout:out,stderr:err}):reject(new Error(err.trim()||out.trim()||`${cmd} exited with code ${code}`)));});
async function renderPdf(url,input,deps){const edge=deps.findEdgeExecutable?.();if(!edge)throw new Error("Microsoft Edge is required for PDF rendering on this machine");const title=input.title||`page-${Date.now()}`;const file=outPath({outputPath:input.outputPath,outputDir:input.outputDir,defaultBaseName:slug(title),extension:".pdf"});await run(edge,["--headless=new","--disable-gpu","--hide-scrollbars","--mute-audio","--no-pdf-header-footer",`--virtual-time-budget=${Math.max(1000,Number(input.waitMs||4000))}`,`--print-to-pdf=${file}`,url]);const stat=fs.statSync(file);return{output_path:file,bytes:stat.size,engine:"edge-headless",source_url:url,title};}
async function shot(url,input,deps){const edge=deps.findEdgeExecutable?.();if(!edge)throw new Error("Microsoft Edge is required for screenshot capture on this machine");const file=outPath({outputPath:input.outputPath,outputDir:input.outputDir,defaultBaseName:slug(input.title||`page-${Date.now()}`),extension:".png"});const width=Number(input.width||1440),height=Number(input.height||2200);await run(edge,["--headless=new","--disable-gpu",`--window-size=${width},${height}`,`--virtual-time-budget=${Math.max(1000,Number(input.waitMs||3500))}`,`--screenshot=${file}`,url]);const stat=fs.statSync(file);return{output_path:file,bytes:stat.size,width,height,engine:"edge-headless"};}
function templateHtml(id,data={},opt={}){const title=opt.title||data.title||"OpenSearch Report";const summary=Array.isArray(data.summary)?data.summary.join("\n"):String(data.summary||data.excerpt||"");const sections=Array.isArray(data.sections)?data.sections:[];const items=Array.isArray(data.items)?data.items:[];if(id==="summary_card")return `<!doctype html><html><head><meta charset="utf-8" /><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;margin:32px;color:#111827}.card{border:1px solid #d1d5db;border-radius:16px;padding:28px}.meta{color:#6b7280;font-size:13px;margin-bottom:18px}</style></head><body><div class="card"><div class="meta">Generated ${esc(new Date().toISOString())}</div><h1>${esc(title)}</h1><p>${esc(summary)}</p><ul>${items.map((i)=>`<li>${esc(String(i))}</li>`).join("")}</ul></div></body></html>`;return `<!doctype html><html><head><meta charset="utf-8" /><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;margin:32px;line-height:1.6;color:#111827}h1,h2,h3{color:#0f172a}.meta{color:#6b7280;font-size:13px;margin-bottom:20px}.panel{border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-bottom:16px}ul{padding-left:20px}</style></head><body><div class="meta">Generated ${esc(new Date().toISOString())}</div><h1>${esc(title)}</h1>${summary?`<section class="panel"><h2>Summary</h2><p>${esc(summary)}</p></section>`:""}${sections.map((s)=>`<section class="panel"><h2>${esc(s.heading||s.title||"Section")}</h2><p>${esc(s.content||s.text||"")}</p></section>`).join("")}${items.length?`<section class="panel"><h2>Highlights</h2><ul>${items.map((i)=>`<li>${esc(String(i))}</li>`).join("")}</ul></section>`:""}</body></html>`;}
const csvMd=(v)=>{const rows=String(v||"").split(/\r?\n/).map((l)=>l.trim()).filter(Boolean).map((l)=>l.split(",").map((x)=>x.trim()));if(!rows.length)return "";return [`| ${rows[0].join(" | ")} |`,`| ${rows[0].map(()=>"---").join(" | ")} |`,...rows.slice(1).map((r)=>`| ${r.join(" | ")} |`)].join("\n");};
const jsonMd=(v)=>{try{return `\`\`\`json\n${JSON.stringify(JSON.parse(v),null,2)}\n\`\`\``;}catch(_){return `\`\`\`json\n${v}\n\`\`\``;}};
function externalMd(inputPath){const cmds=[];if(process.env.OPENSEARCH_MARKITDOWN_CMD){const [cmd,...args]=process.env.OPENSEARCH_MARKITDOWN_CMD.split(" ").filter(Boolean);if(cmd)cmds.push([cmd,[...args,inputPath]]);}cmds.push(["markitdown",[inputPath]],["python",["-m","markitdown",inputPath]],["py",["-m","markitdown",inputPath]]);for(const [cmd,args] of cmds){try{const r=spawnSync(cmd,args,{encoding:"utf8"});if(r.status===0&&r.stdout?.trim())return{markdown:r.stdout.trim(),engine:`${cmd}${args.length?` ${args[0]}`:""}`};}catch(_){}}return null;}
function fileToMd(inputPath){const abs=path.resolve(inputPath);const ext=path.extname(abs).toLowerCase();const raw=fs.readFileSync(abs);const txt=[".md",".txt",".html",".htm",".json",".csv",".tsv"].includes(ext)?raw.toString("utf8"):null;if(ext===".md")return{markdown:txt,engine:"native-markdown"};if(ext===".txt")return{markdown:txt,engine:"native-text"};if(ext===".html"||ext===".htm")return{markdown:htmlToMd(txt),engine:"native-html"};if(ext===".json")return{markdown:jsonMd(txt),engine:"native-json"};if(ext===".csv"||ext===".tsv")return{markdown:csvMd(txt.replace(/\t/g,",")),engine:"native-delimited"};const external=externalMd(abs);if(external)return external;throw new Error(`Unsupported file type for local conversion: ${ext||"unknown"}. Install markitdown or set OPENSEARCH_MARKITDOWN_CMD for office/PDF files.`);}
async function extractArticle(input,deps){const {html,finalUrl}=await fetchHtml(input.url,input);const rendered=input.render?await deps.captureRenderedPage?.(input.url,{waitMs:input.waitMs}):null;return articlePayload({url:input.url,finalUrl,html,rendered});}
function registerProductivityTools(ToolRegistry,deps={}){
  ToolRegistry.registerTool({id:"extract_readable_article",name:"Readable Article Extractor",description:"Extract the main article body, metadata, and useful links from a web page",parameters:[{name:"url",type:"string",required:true,description:"Target page URL"},{name:"render",type:"boolean",required:false,description:"Use browser rendering snapshot"},{name:"waitMs",type:"number",required:false,description:"Optional browser wait time in milliseconds"}],validate(input){if(!input?.url||typeof input.url!=="string")throw new Error("url is required and must be a string");},async execute(input){return extractArticle(input,deps);},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"extract_web_page_bundle",name:"Web Page Bundle Extractor",description:"Fetch a page once and return reusable markdown/html/text bundles plus optional screenshot",parameters:[{name:"url",type:"string",required:true,description:"Target page URL"},{name:"formats",type:"array",required:false,description:"Requested formats such as markdown/html/text/json"},{name:"render",type:"boolean",required:false,description:"Use browser rendering snapshot"},{name:"includeScreenshot",type:"boolean",required:false,description:"Capture screenshot with Edge"},{name:"outputDir",type:"string",required:false,description:"Output directory for generated assets"}],validate(input){if(!input?.url||typeof input.url!=="string")throw new Error("url is required and must be a string");if(input.formats!==undefined&&!Array.isArray(input.formats))throw new Error("formats must be an array when provided");},async execute(input){const article=await extractArticle(input,deps);const bundle={url:article.url,final_url:article.final_url,title:article.title,excerpt:article.excerpt,formats:Array.isArray(input.formats)&&input.formats.length?input.formats.map((v)=>String(v).toLowerCase()):["markdown","html","text"],headings:article.headings,links:article.links,meta:article.meta};if(bundle.formats.includes("html"))bundle.html=article.content_html;if(bundle.formats.includes("text"))bundle.text=article.text;if(bundle.formats.includes("markdown"))bundle.markdown=htmlToMd(article.content_html);if(bundle.formats.includes("json"))bundle.json=article;if(input.includeScreenshot)bundle.screenshot=await shot(input.url,{outputDir:input.outputDir,title:article.title||"page",waitMs:input.waitMs},deps);return bundle;},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"extract_structured_web_data",name:"Structured Web Data Extractor",description:"Extract structured JSON fields from a web page using deterministic metadata and content heuristics",parameters:[{name:"url",type:"string",required:true,description:"Target page URL"},{name:"fields",type:"array",required:false,description:"Field names to extract"},{name:"schema",type:"string",required:false,description:"Schema definition as JSON string or field list"},{name:"render",type:"boolean",required:false,description:"Use browser rendering snapshot"}],validate(input){if(!input?.url||typeof input.url!=="string")throw new Error("url is required and must be a string");},async execute(input){const article=await extractArticle(input,deps);const fields=schemaFields(input);const structured={};for(const field of fields.length?fields:["title","description","author","published_at","site_name","canonical_url"])structured[field]=inferField(field,{article,meta:article.meta,jsonLd:article.json_ld,text:article.text});return{url:article.url,title:article.title,fields:fields.length?fields:Object.keys(structured),structured_data:structured,source_summary:{excerpt:article.excerpt,word_count:article.word_count,headings:article.headings.slice(0,8)},extraction_engine:"deterministic-web-schema"};},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"url_to_pdf",name:"URL to PDF",description:"Render a live web page to PDF using headless Edge",parameters:[{name:"url",type:"string",required:true,description:"Target page URL"},{name:"outputPath",type:"string",required:false,description:"Absolute or relative PDF output path"},{name:"outputDir",type:"string",required:false,description:"Output directory when outputPath is not set"},{name:"title",type:"string",required:false,description:"Preferred output file title"},{name:"waitMs",type:"number",required:false,description:"Virtual time budget before print"}],validate(input){if(!input?.url||typeof input.url!=="string")throw new Error("url is required and must be a string");},async execute(input){return renderPdf(input.url,input,deps);},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"html_to_pdf",name:"HTML to PDF",description:"Render raw HTML content to PDF",parameters:[{name:"html",type:"string",required:true,description:"HTML content"},{name:"outputPath",type:"string",required:false,description:"Absolute or relative PDF output path"},{name:"outputDir",type:"string",required:false,description:"Output directory when outputPath is not set"},{name:"title",type:"string",required:false,description:"Document title"}],validate(input){if(!input?.html||typeof input.html!=="string")throw new Error("html is required and must be a string");},async execute(input){const file=tmp(".html",input.html);try{return await renderPdf(`file:///${file.replace(/\\/g,"/")}`,{...input,title:input.title||"html-document"},deps);}finally{rm(file);}},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"markdown_to_pdf",name:"Markdown to PDF",description:"Render Markdown content to PDF through an HTML bridge",parameters:[{name:"markdown",type:"string",required:true,description:"Markdown content"},{name:"outputPath",type:"string",required:false,description:"Absolute or relative PDF output path"},{name:"outputDir",type:"string",required:false,description:"Output directory when outputPath is not set"},{name:"title",type:"string",required:false,description:"Document title"}],validate(input){if(!input?.markdown||typeof input.markdown!=="string")throw new Error("markdown is required and must be a string");},async execute(input){const file=tmp(".html",mdToHtml(input.markdown,input.title||"Markdown Document"));try{return await renderPdf(`file:///${file.replace(/\\/g,"/")}`,{...input,title:input.title||"markdown-document"},deps);}finally{rm(file);}},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"template_to_pdf",name:"Template to PDF",description:"Render report templates such as research_report or summary_card into a PDF",parameters:[{name:"templateId",type:"string",required:true,description:"Template identifier"},{name:"data",type:"object",required:false,description:"Template data"},{name:"outputPath",type:"string",required:false,description:"Absolute or relative PDF output path"},{name:"outputDir",type:"string",required:false,description:"Output directory when outputPath is not set"},{name:"title",type:"string",required:false,description:"Document title"}],validate(input){if(!input?.templateId||typeof input.templateId!=="string")throw new Error("templateId is required and must be a string");},async execute(input){const file=tmp(".html",templateHtml(input.templateId,input.data||{},{title:input.title}));try{return await renderPdf(`file:///${file.replace(/\\/g,"/")}`,{...input,title:input.title||input.templateId},deps);}finally{rm(file);}},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"compose_pdf_packet",name:"PDF Packet Composer",description:"Compose multiple markdown, HTML, or text sections into one PDF packet",parameters:[{name:"sections",type:"array",required:true,description:"Section objects with title and markdown/html/text"},{name:"title",type:"string",required:false,description:"Packet title"},{name:"outputPath",type:"string",required:false,description:"Absolute or relative PDF output path"},{name:"outputDir",type:"string",required:false,description:"Output directory when outputPath is not set"}],validate(input){if(!Array.isArray(input?.sections)||!input.sections.length)throw new Error("sections must be a non-empty array");},async execute(input){const md=[`# ${input.title||"PDF Packet"}`,...input.sections.map((s,i)=>`\n## ${s.title||`Section ${i+1}`}\n\n${s.markdown||(s.html?htmlToMd(s.html):null)||s.text||""}`)].join("\n");const file=tmp(".html",mdToHtml(md,input.title||"PDF Packet"));try{return await renderPdf(`file:///${file.replace(/\\/g,"/")}`,{...input,title:input.title||"pdf-packet"},deps);}finally{rm(file);}},source:"builtin",status:"active"});
  ToolRegistry.registerTool({id:"file_to_markdown",name:"File to Markdown",description:"Convert local files to Markdown using native adapters and optional MarkItDown fallback",parameters:[{name:"inputPath",type:"string",required:true,description:"Local file path"},{name:"outputPath",type:"string",required:false,description:"Optional output markdown path"}],validate(input){if(!input?.inputPath||typeof input.inputPath!=="string")throw new Error("inputPath is required and must be a string");if(!fs.existsSync(path.resolve(input.inputPath)))throw new Error("inputPath does not exist");},async execute(input){const {markdown,engine}=fileToMd(input.inputPath);let outputPath=null;if(input.outputPath){outputPath=path.resolve(input.outputPath);ensure(path.dirname(outputPath));fs.writeFileSync(outputPath,markdown,"utf8");}return{input_path:path.resolve(input.inputPath),output_path:outputPath,markdown,engine};},source:"builtin",status:"active"});
}

module.exports={registerProductivityTools};
